TRAIN:
    model: resnet50
    N: 4
    M: 8
    sparse_optimizer: 1

    workers: 8
    batch_size: 256
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.00005

    print_freq: 20
    model_dir: /nvme1/vchua/run/nm-sparsity/rn50_4oo8_run

    train_root: /nvme1/datasets/ilsvrc2012/torchvision/train
    train_source: /nvme1/datasets/ilsvrc2012/torchvision/meta/train.txt
    val_root: /nvme1/datasets/ilsvrc2012/torchvision/val
    val_source: /nvme1/datasets/ilsvrc2012/torchvision/meta/val.txt


TEST:
    checkpoint_path : /nvme1/vchua/run/sr-ste-zoo/rn50-4oo8.pth
