TRAIN:
    model: resnet50
    N: 2
    M: 4
    sparse_optimizer: 1

    workers: 6
    batch_size: 256
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.00005


    print_freq: 100
    model_dir: /data1/vchua/nm-sparsity/checkpoint/resnet50_2by4

    train_root: /data/dataset/imagenet/ilsvrc2012/torchvision/train
    train_source: /data/dataset/imagenet/ilsvrc2012/torchvision/meta/train.txt
    val_root: /data/dataset/imagenet/ilsvrc2012/torchvision/val
    val_source: /data/dataset/imagenet/ilsvrc2012/torchvision/meta/val.txt




TEST:
    checkpoint_path : /data1/vchua/nm-sparsity/data/pretrained_model/
